### ISSUE TITLE
Bug in pagination for transactions listing

### ISSUE THREAD

**Issue by bibekblockchain** [Ashlar/zilliqa-js-viewblock#14]
I tried to list the transactions for Zilliqa using `https://api.viewblock.io/v2/zilliqa/addresses/zil14jmjrkvfcz2uvj3y69kl6gas34ecuf2j5ggmye/txs?network=testnet&type=tokenContract&page=2` but got `nextPage: "21"`. It is string while it was supposed to be number. Maybe issue with concatenation of string and number ("2"+1)
 
<img width="236" alt="Screen Shot 2021-09-02 at 3 21 09 AM" src="https://user-images.githubusercontent.com/24819893/131748644-3d3e30f2-93c2-4805-aa9d-ebfc4e691352.png">

**Comment by balthazar** [comment]
Thanks for the report, the fix is deploying as I type this
