### ISSUE TITLE
How to get API key?

### ISSUE THREAD

**Issue by mchalise** [Ashlar/zilliqa-js-viewblock#21]
I tried to go to the viewblock link but there is no option to sign up or create an API key.
Any help here?

**Comment by mchalise** [comment]
@b3e @diffusedt @balthazar  Help here. 🥺

**Comment by balthazar** [comment]
Hello @mchalise

Can you try to get one on v1.viewblock.io? We are refactoring our API, thus why it is disabled on our main website. Send an email to contact@viewblock.io if you're having issues!

PS: b3e is not part of Viewblock
